In [1]:
%%bash
sudo pip install pychemkin

sudo: no tty present and no askpass program specified


In [2]:
import numpy as np
from pychemkin import chemkin
demofile = 'demo_xml/rxns_reversible.xml'
rxnsystem = chemkin(demofile)
T = 999.99999 #temperature in K
x = [1,2,3,4,5,6,7,8]
print("Progress rates")
print(rxnsystem.progress_rate(x,T))
print("Reaction rates")
print(rxnsystem.reaction_rate(x,T))

Finished reading xml input file
Progress rates
[ -4.37918361e+16   1.06891625e+13   5.80849020e+13  -3.33238238e+15
   1.05248391e+14   4.78255724e+14   4.55000000e+14   6.44285996e+14
   1.19599129e+14   1.48165394e+14   9.47751873e+13]
Reaction rates
[  4.30093415e+16  -4.10199181e+16  -4.95223968e+16   1.84639721e+14
   4.15435240e+15   4.49963705e+16  -1.43984953e+15  -3.62539710e+14]


In [3]:
rxnsystem

chemkin('demo_xml/rxns_reversible.xml')

In [4]:
rxnsystem.species

['H', 'O', 'OH', 'H2', 'H2O', 'O2', 'HO2', 'H2O2']

In [5]:
print(rxnsystem)

['H + O2 [=] O + OH', 'O + H2 [=] H + OH', 'H2 + OH [=] H2O + H', 'O + H2O [=] OH + OH', 'HO2 + H [=] H2 + O2', 'HO2 + H [=] OH + OH', 'HO2 + O [=] O2 + OH', 'HO2 + OH [=] H2O + O2', 'H2O2 + H [=] H2O + OH', 'H2O2 + H [=] HO2 + H2', 'H2O2 + O [=] OH + HO2']
chemical equations:
[
H + O2 [=] O + OH
O + H2 [=] H + OH
H2 + OH [=] H2O + H
O + H2O [=] OH + OH
HO2 + H [=] H2 + O2
HO2 + H [=] OH + OH
HO2 + O [=] O2 + OH
HO2 + OH [=] H2O + O2
H2O2 + H [=] H2O + OH
H2O2 + H [=] HO2 + H2
H2O2 + O [=] OH + HO2
]
species: not specified
nu_react:
[[1 0 0 0 1 1 0 0 1 1 0]
 [0 1 0 1 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1]]
nu_prod:
[[0 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 2 0 2 1 0 1 0 1]
 [0 0 0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]]
reaction coefficients:
[
modifiedArrhenius Reactio

In [1]:
#import sys
#sys.path.append('../')
from pychemkin import ChemSolver, chemkin
import numpy as np

In [10]:
%%bash
pwd


/Users/kimia/Desktop/CS207/final/cs207-FinalProject/demo_notebook


In [16]:
%%bash
ls

demo.ipynb
demo_ODESolver.ipynb
demo_equilibrium.ipynb
demo_xml
testing_viz.ipynb


In [3]:
%%bash
pip uninstall --yes pychemkin
pip install numpy scipy pandas --upgrade
#cd /tmp/cs207-FinalProject/
python setup.py install # please change the path


Uninstalling pychemkin-1.0.8:
  Successfully uninstalled pychemkin-1.0.8
Requirement already up-to-date: numpy in /anaconda/lib/python3.6/site-packages
Requirement already up-to-date: scipy in /anaconda/lib/python3.6/site-packages
Requirement already up-to-date: pandas in /anaconda/lib/python3.6/site-packages
Requirement already up-to-date: python-dateutil>=2 in /anaconda/lib/python3.6/site-packages (from pandas)
Requirement already up-to-date: pytz>=2011k in /anaconda/lib/python3.6/site-packages (from pandas)
Requirement already up-to-date: six>=1.5 in /anaconda/lib/python3.6/site-packages (from python-dateutil>=2->pandas)


python: can't open file 'setup.py': [Errno 2] No such file or directory


In [11]:
chem = chemkin("rxns2.xml")

Finished reading xml input file


ValueError: Database /anaconda/lib/python3.6/site-packages/pychemkin-1.0.8-py3.6.egg/pychemkin/data/thermo.sqlite does not exist

In [4]:
chem = chemkin("demo_xml/rxns.xml")
# initial concentration
x_init = [1]*6
T = 1000
# time series you want
ts = 1.e-7
# set to (min val in ts, max val in ts)
t_max = 5.e-5
cs = ChemSolver(chem).solve(x_init, T, t_max, ts)
df = cs.to_df()
df.head()

Finished reading xml input file


ValueError: Database /anaconda/lib/python3.6/site-packages/pychemkin-1.0.8-py3.6.egg/pychemkin/data/thermo.sqlite does not exist